name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql root password: 123456
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package

    - name: Install AWS CLI
      run: sudo apt-get update && sudo apt-get install -y awscli
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region ${{ secrets.AWS_REGION }}
      
    - name: Setup HashiCorp Packer
      uses: hashicorp/setup-packer@v2.0.0
    - name: Pakcer init
      run: packer init packer.pkr.hcl
    - name: Packer Validate
      run: packer validate packer.pkr.hcl
    - name: Build AMI
      run: packer build  packer.pkr.hcl | tee output.txt
    - name: Get AMI Id
      run: echo -n $(tail -n 5 output.txt | grep ami | awk '{print $NF}') > ami_id.txt
      
    - name: Share AMI to Demo
      env:
        AWS_DEMO_ACCOUNT: ${{ secrets.AWS_DEMO_ACCOUNT }}
      run: aws ec2 modify-image-attribute --image-id $(cat ami_id.txt) --launch-permission "Add=[{UserId=$AWS_DEMO_ACCOUNT}]"

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.0
    - name: Terraform Init
      run: terraform init
    - name: Terraform Apply
      run: terraform apply -auto-approve
